remote_theme: b2a3e8/jekyll-theme-console
title: About Henrik
description: In this page you will find Henrik Ferrara's updated bio. Bookmark this page to frequently check on updates!
email: henrikferrara@gmail.com
header_pages: 
- index.markdown
- cv.markdown
- updates.markdown
- soundmusic.markdown

style: dark

footer: "Henrik Ferrara Ω 2022"

collections:
    music:
        output: true
        
github_username:  henrikferrara
plugins:
  - jekyll-feed
  - jekyll-seo-tag
