remote_theme: b2a3e8/jekyll-theme-console
title: Henrik Ferrara
description: In this page you will find Henrik Ferrara's updated bio. Bookmark this page to frequently check on updates!
email: henrikferrara@gmail.com
header_pages: 
- index.md
- cv.md
- updates.md
- soundmusic.md
- stable.md


style: dark

baseurl: ""
url: "https://henrikferrara.github.io"

footer: "Henrik Ferrara Ω 2024"

collections:
    music:
        output: true
        
github_username:  henrikferrara
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
